# 6. Sistemi di equazioni lineari

## 6.1. Introduzione a numpy
Il pacchetto numpy consente la manipolazione di vettori multidimensionali e le loro operazioni caratteristiche prodotto scalare, vettoriale, moltiplicaizone matriciale... con questo pacchetto è possibile fare molte delle operazioni consentite nel linguaggio Matlab/Octave.

In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3,4,5,6])

In [3]:
x

array([1, 2, 3, 4, 5, 6])

In [4]:
#prodotto scalare
x.dot(x)

91

In [5]:
#prodotto vettoriale (solo per dimensione 2 o 3), notare come una lista viene considerata automaticamente un vettore
np.cross([1,2,3],[3,2,1])

array([-4,  8, -4])

In [6]:
#ecco una matrice, inizializzata come lista di lista
np.array([[1,2,3,4],[2,0,1,1],[0,0,1,0],[1,0,0,4]])

array([[1, 2, 3, 4],
       [2, 0, 1, 1],
       [0, 0, 1, 0],
       [1, 0, 0, 4]])

In [7]:
A=np.array([[1,2,3,4],[2,0,1,1],[0,0,1,0],[1,0,0,4]])
#prodotto matrice-vettore
A.dot([1,0,1,0])

array([4, 3, 1, 1])

In [8]:
#trasposta
A.T

array([[1, 2, 0, 1],
       [2, 0, 0, 0],
       [3, 1, 1, 0],
       [4, 1, 0, 4]])

In [9]:
#prodotto fra matrici
np.dot(A,A.T)

array([[30,  9,  3, 17],
       [ 9,  6,  1,  6],
       [ 3,  1,  1,  0],
       [17,  6,  0, 17]])

In [10]:
#determinante
np.linalg.det(A)

-14.000000000000004

In [11]:
#dimensioni
A.shape

(4, 4)

In [12]:
#lindicizzazione di un vettore/matrice avviene come per le liste
A[1:,:2]

array([[2, 0],
       [0, 0],
       [1, 0]])

In [13]:
#una matrice può essere trasformata in un lungo vettore
A.flatten()

array([1, 2, 3, 4, 2, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 4])

In [14]:
#..o cambiata di forma
A.reshape((2,8))

array([[1, 2, 3, 4, 2, 0, 1, 1],
       [0, 0, 1, 0, 1, 0, 0, 4]])

In [15]:
A.reshape(-1)

array([1, 2, 3, 4, 2, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 4])