# 6. Sistemi di equazioni lineari

## 6.2. Cramer contro Gauss
Il pacchetto numpy ha diversi solutori di equazioni lineari. Vediamoli insieme e cerchiamo di scrivere autonomamente le nostre functions.

In [1]:
import numpy as np
A=np.array([[1,2,3,4.5],[0,2,0,-1],[0,0,1,0],[1.5,0,0,1.4]])
b=np.array([1,0,4,1])

In [2]:
np.linalg.solve(A,b)

array([ 3.05109489, -1.27737226,  4.        , -2.55474453])

In [3]:
#vediamo se torna
x=np.linalg.solve(A,b)
A.dot(x)

array([1., 0., 4., 1.])

### Ricordiamo il metodo di Cramer che risolve il sistema lineare $Ax=b$ con i determinanti
$$x_i = \frac{det(A_i)}{det(A)}$$
dove A_i è la matrice A in cui ho sotituito l'i-esima colonna di A con il vettore $b$

In [4]:
def cramer(A,b):
    dtA=np.linalg.det(A)
    x=np.zeros(b.shape)
    for i in range(len(x)):
        Ai=A.copy()
        Ai[:,i]=b.reshape(-1)
        x[i]=float(np.linalg.det(Ai))/float(dtA)
    return x

In [5]:
cramer(A,b)

array([ 3.05109489, -1.27737226,  4.        , -2.55474453])

In [6]:
#controlliamo
x=cramer(A,b)
A.dot(x)

array([ 1.0000000e+00, -8.8817842e-16,  4.0000000e+00,  1.0000000e+00])

Oltre ad un accuratezza minore, verificabile con una qualunque norma vettoriale, Cramer diventa problematicamente lento per sistemi di ordine grande. Il suo costo computazionale è infatti di ordine esponenziale. Questi ragionamenti possono essere riportati agli studenti in modo semplice, in modo da svilupparne pian piano l'intuito computazionale. Si può dire infatti che il determinante è lento da calcolare. Vediamo un esempio.

### Vediamo adesso il metodo di Gauss:
Il Metodo di eliminazione di Gauss (MEG) si prefigge di ridurre una matrice alla forma triangolare superiore (o a scalini) in modo da risolvere il sitema per sostituzione successiva.

In [7]:
def MEG(A,b):
    A=np.array(A,dtype="float")
    b=np.array(b,dtype="float")
    x=np.zeros(b.shape)
    #triangolarizzazione
    n=len(b)
    for i in range(n-1):
        for j in range(i+1,n):
            m=A[j,i]/A[i,i]
            A[j,i:]-=m*A[i,i:]
            b[j]-=m*b[i]
    #sostituzioni
    x[-1]=b[-1]/A[-1,-1]
    for k in range(0,n-1)[::-1]:
        x[k]=(b[k]-np.dot(A[k,k+1:],x[k+1:]))/A[k,k]
    return x

In [8]:
A=np.array([[1,2,3,4.5],[0,2,0,-1],[0,0,1,0],[1.5,0,0,1.4]])
b=np.array([1,0,4,1])
MEG(A,b)

array([ 3.05109489, -1.27737226,  4.        , -2.55474453])

In [9]:
x=MEG(A,b)
A.dot(x)

array([1., 0., 4., 1.])